version: '3.8'
services:
  postgres:
    build: ./postgres
    container_name: cron-postgres
    restart: always
    environment:
      POSTGRES_USER: cron
      POSTGRES_PASSWORD: cronpass
      POSTGRES_DB: cron_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
